@startuml ActivityDiagram

skinparam activity {
    BackgroundColor PaleGreen
    BorderColor DarkSlateGray
    StartColor DarkSlateGray
    EndColor DarkSlateGray
    ArrowColor DarkSlateGray
}

title 8-Puzzle Solver Activity Diagram

start

partition GameController {
    :Print Instructions;
    :Get User Input;
    :Process User Input;
}

partition PuzzleSolver {
    if (Is input solvable?) then (yes)
        partition EightPuzzleProblem {
            :Solve Puzzle;
        }
        partition GameController {
            :Print Solution;
        }
    else (no)
        partition GameController {
            :Print Not Solvable;
        }
    endif
}

partition GameController {
    :Handle Exceptions;
}
stop

@enduml
