@startuml SequenceDiagram

skinparam sequence {
    ArrowColor DarkSlateGray
    ActorBorderColor DarkSlateGray
    LifeLineBorderColor DarkSlateGray
    LifeLineBackgroundColor PaleGreen
    ParticipantBorderColor DarkSlateGray
    ParticipantBackgroundColor PaleGreen
    ParticipantFontName Roboto
    ActorBackgroundColor PaleGreen
    ActorFontName Roboto
    TitleFontSize 24
    TitleFontColor DarkOliveGreen
}

title 8-Puzzle Solver Sequence Diagram

actor User

User -> GameController: Start Program
activate GameController
GameController -> User: Display Instructions
User -> GameController: Input Puzzle
GameController -> PuzzleSolver: isSolvable(digit_list)
activate PuzzleSolver
PuzzleSolver --> GameController: Solvable
deactivate PuzzleSolver
GameController -> EightPuzzleProblem: Solve Puzzle (astar)
activate EightPuzzleProblem
EightPuzzleProblem --> GameController: Solution
deactivate EightPuzzleProblem
GameController -> User: Display Solution
deactivate GameController

@enduml
